const cards = [
  {
    name: "Webpack",
    type: "Bundler",
    description:
      "Webpack is a tool that puts all the pieces of a web application together. \nIt helps improve the performance of the application and makes it easier to manage. \nWebpack is configured using a file that tells it how to put everything together.",
    monthlyDownloads: 100,
    features: ["f1", "f2", "f3"],
    pros: [
      "Most powerful bundler",
      "Built-in dev server with live-reload",
      "Can handle all types of assets",
    ],
    cons: ["c1", "c2", "c3"],
  },
  {
    name: "Browserify",
    type: "Bundler",
    description: "Browserify description",
    monthlyDownloads: 100,
    features: ["f1", "f2", "f3"],
    pros: ["p1", "p1", "p1"],
    cons: ["c1", "c2", "c3"],
  },
  {
    name: "Parcel",
    type: "Bundler",
    description: "Parcel description",
    monthlyDownloads: 100,
    features: ["f1", "f2", "f3"],
    pros: ["p1", "p1", "p1"],
    cons: ["c1", "c2", "c3"],
  },
  {
    name: "React",
    type: "Frontend Framework",
    description: "React description",
    monthlyDownloads: 100,
    features: ["f1", "f2", "f3"],
    pros: ["p1", "p1", "p1"],
    cons: ["c1", "c2", "c3"],
  },
  {
    name: "Angular",
    type: "Frontend Framework",
    description: "Angular description",
    monthlyDownloads: 100,
    features: ["f1", "f2", "f3"],
    pros: ["p1", "p1", "p1"],
    cons: ["c1", "c2", "c3"],
  },
  {
    name: "Vue",
    type: "Frontend Framework",
    description: "Vue description",
    monthlyDownloads: 100,
    features: ["f1", "f2", "f3"],
    pros: ["p1", "p1", "p1"],
    cons: ["c1", "c2", "c3"],
  },
  {
    name: "Express",
    type: "Backend Framework",
    description: "Express description",
    monthlyDownloads: 100,
    features: ["f1", "f2", "f3"],
    pros: ["p1", "p1", "p1"],
    cons: ["c1", "c2", "c3"],
  },
  {
    name: "Ruby on Rails",
    type: "Backend Framework",
    description: "Ruby on Rails description",
    monthlyDownloads: 100,
    features: ["f1", "f2", "f3"],
    pros: ["p1", "p1", "p1"],
    cons: ["c1", "c2", "c3"],
  },
  {
    name: "Flask",
    type: "Backend Framework",
    description: "Flask description",
    monthlyDownloads: 100,
    features: ["f1", "f2", "f3"],
    pros: ["p1", "p1", "p1"],
    cons: ["c1", "c2", "c3"],
  },
];

module.exports = cards;
